enhance ee.Image.fullLike
gee-community/geetools pull request #266
Opened 2024-05-15 17:45 UTC by fitoprincipe

`ee.Projection` not only stores the CRS but also the nominal scale, and although the CRS is usually constant across all bands, is not the same for the nominal scale (example [here](https://code.earthengine.google.com/86d798c3bee32855b5cbfb24d92037f2)). So, one of the modification of this PR is to copy each band's projection to the image generated by `ee.Image.fullLike`.

In the previous version of `fullLike` the footprint of the original images was passed to the resulting image. Now the user can choose whether to copy it or not, giving more flexibility to the user.

2024-05-15 19:20 UTC, fitoprincipe commented
test failure is weird since the failing test is not using the modified method at all 🤔

2024-05-16 06:19 UTC, 12rambau commented
The test failure is related to GEE slightly changing it's rounding method all the time.

2024-05-16 06:26 UTC, 12rambau requested changes

2024-05-16 06:26 UTC, 12rambau commented on geetools/Image/__init__.py
> +            lambda b: image.select([b]).reproject(self._obj.select([b]).projection())
I think you don't need to use the `[` in select (https://developers.google.com/earth-engine/apidocs/ee-image-select).

2024-05-17 06:40 UTC, 12rambau approved these changes

2024-05-17 06:40 UTC, merged