ee.Dictionary.toTable + tests
gee-community/geetools pull request #372
Opened 2024-11-05 01:09 UTC by fitoprincipe

https://github.com/gee-community/geetools/pull/368#pullrequestreview-2412434217

2024-11-22 23:36 UTC, 12rambau requested changes

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
I would use the same pattern as the other to maintain one single return statement: 

```suggestion
            features = ee.list(ee.Feature(None, self._obj))
```

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
This leads to 2 very differnet ways of treating the dictionnary keys and I think it's more confusing than helping. At the end of the day, the use case is when the keys of the dict are the future `system:index` of the features. The case were the keys are simply treated as column names is so trivial (`f = ee.Feature(, None, self._obj)`) that I think it should not be accepted as an input of this function. 

Narrowing down the use cases will also make it easier to understand the first sentence of the docstring "The keys will always be stored in `system:index` column."

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            return feat.set(ee.Dictionary(value))
Alternative building blocks. I think setting all the props at once makes it easier to understand what the function is doing. As there is no line gain, it's up to you to decide which one is better

```suggestion
            index = {"system:index": ee.String(key)}
            props = ee.Dictionary(value).combine(index)
            return ee.Feature(None, props)
```

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            return feat.set(properties)
Alternative building blocks: 
```suggestion
            index = {"system:index" : ee.String(key)}
            values = ee.List(value)
            columns = ee.List.sequence(1, value.size())
            columns = columns.map(lambda k: ee.String("value_").cat(ee.Number(k).toInt()))
            props = ee.Dictionary.fromLists(columns, values).combine(index)
            return ee.Feature(None, props)
```

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            keys = ee.List.sequence(1, value.size())
any reason why the values index starts at 1 instead of 0 ?

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        The keys will always be stored in `system:index` column.
The long description needs to be improved so the user can understand exactly what this function is doing with both the keys and the values. In the current implementation, the default behaviour (1 feature, non-collection dType) is not described.

2024-11-22 23:36 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        """Convert a ee.Dictionary to a ee.FeatureCollection with no geometries (table).
We now have full support of intersphinx so let's use it as much as we can: 

```suggestion
        """Convert a :py:class:`ee.Dictionary` to a :py:class:`ee.FeatureCollection` with no geometries (table).
```

2025-01-09 18:20 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
Hm, I am not sure if I understand this comment. The code you highlighted is not to handle different types of keys but  different type of values (that's why it's called `valueType`). You can have a look in the tests:

when values are in a list: https://github.com/gee-community/geetools/blob/8eafa4a14c9bfc6da9a8c56d411e526aa0e255a2/tests/test_Dictionary.py#L44

when values are in a dict: https://github.com/gee-community/geetools/blob/8eafa4a14c9bfc6da9a8c56d411e526aa0e255a2/tests/test_Dictionary.py#L49-L54

and for other types (`ee.String` in this case): https://github.com/gee-community/geetools/blob/8eafa4a14c9bfc6da9a8c56d411e526aa0e255a2/tests/test_Dictionary.py#L39

2025-01-09 18:43 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            keys = ee.List.sequence(1, value.size())
I guess no, would you prefer it to start at 0? For me it's the same, because actually to me the most important process is reversing this process in the client side (`ee.Dictionary` --> `ee.FeatureCollection` --(export)--> `geopandas.GeoDataFrame` --> `dict`).. the first and the last objects should be equivalent.

2025-01-09 22:39 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
that's the point, option 1 and 2 works the same: Take the root keys (Argentina and Armenia) and make it the system:index and then find a clever way to deal with the values
The option 3 only create 1 single feature where the root keys are the properties. 

my point is that option 3 is the 1 liner i put in my comment and should not be covered by this function. Only the 2 first one. making this part of the docstring (`The keys will always be stored in `system:index` column.`) true.

2025-01-09 22:41 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            keys = ee.List.sequence(1, value.size())
I think all index start at 0 in GEE (list, bands etc...) so I would keep ourselves consistent with it.

2025-01-10 12:05 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
I see what you mean, but I am not convinced that we should not cover option 3 at all. What if I change the approach on how to handle it?? To respect the concept of `the keys will always be stored in system:index column`, the resulting table could have always two columns: `system:index` and `item`. So the only difference between option 1, 2 and 3 will the name of the columns other than `system:index`. 

There will also be cases not covered by this function and the user will need to handle the dictionary first in order to be in one of the 3 accepted patterns. For exampe, the result of the reducer `ee.Reducer.fixedHistogram` is a one-key dict where the value is an `ee.Array` as follows

```
{
    thekey: [ 
        [1, 10],
        [2, 20],
        [3, 30],
    ]
}
```

2025-01-10 12:30 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            return ee.FeatureCollection([ee.Feature(None, self._obj)])
I pushed my new proposal

2025-01-13 11:47 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +        The keys will always be stored in `system:index` column.
I pushed my proposal

2025-01-13 12:41 UTC, 12rambau requested changes

2025-01-13 12:41 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            props = {"system:index": ee.String(key), "value": value}
I remember opening this issue some time ago on the GEE tracker: https://issuetracker.google.com/issues/329106322
Isn't it exactly your use case ?

2025-01-13 12:41 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        column "value".
In rst, the content of a paragraph should meet the indetnation after the "x." or "-". In your case that would do something like: 

```suggestion
        1. Any (default): when values are a `ee.String` or `ee.Number`, the
           keys will be saved in the column "system:index" and the values in the
           column "value".
```

2025-01-13 12:41 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            ]}
I would move it to an `Examples` section. you can do the 3 of them and jupyter execute will display the results.

2025-01-13 12:41 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        if valueType == ee.Dictionary:
insterad of object could we use a lighter typing like str with 3 options: "dictionary", "list", "scalar".
In this case scalar would be to mimick pandas terminology but that could of course be anything else. 

If we go this way then instead of an if you could create a dictionary like: 
```python 
make_features{
    "list": feature_from_list,
    "dictionary": feature_from_dictionary,
    "scalar": feature_from_any
}
features = self._obj.map(make_features).values()

return ee.FeatureCollection(features)
```

That's the most pythonic way of doing a switch in python. Alternatively as we are only supporting Python >=3.10, you could also use the `match` statement which have the "else" option to raise error.

2025-01-13 12:52 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            props = {"system:index": ee.String(key), "value": value}
I think no, because AFAIK `ee.Dictionary`'s keys are always strings, that's why I am casting to `ee.String` directly (just to be sure, probably not casting it would work either).

2025-01-13 12:53 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +        if valueType == ee.Dictionary:
Totally agree. I also prefer this way and have done it many times. Not sure why this time I used the old fashion `if.. else..` statement, but I can improve it for sure.

2025-01-13 13:13 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            ]}
what about the output? is it ok as I did?

```
>> this is the content of the output
```

2025-01-13 13:44 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +        if valueType == ee.Dictionary:
I'm not convinced about `scalar` 🤔 What about `any`? we could let the user have any type of value and it will fail if it's not suitable as a valid property value.

2025-01-13 13:55 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            ]}
If you use the Jupyter_execute directive as in the examples of other methods the result is computed on the fly

2025-01-13 14:19 UTC, fitoprincipe commented on geetools/ee_dictionary.py
> +            ]}
ok, so I could remove the "expected result" 👍

2025-01-13 18:17 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                d.geetools.toTable().getInfo()
I created a specific way of making the example self-executable and this rely massively on jupyter-sphinx let me make change proposal for all of them: 

```suggestion
            .. jupyter-execute::
            
                import ee, geetools
                from geetools.utils import initialize_documentation

                initialize_documentation()

                d = ee.Dictionary({"foo": 1, "bar": 2})
                d.geetools.toTable().getInfo()
```

2025-01-13 18:18 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                ee.Initialize()
```suggestion
            .. jupyter-execute::

                import ee, geetools
                from geetools.utils import initialize_documentation
                
                initialize_documentation()
```

2025-01-13 18:18 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                ee.Initialize()
```suggestion
            .. jupyter-execute::
            
                import ee, geetools
                from geetools.utils import initialize_documentation
                
                initialize_documentation()
```

2025-01-13 18:19 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                ee.Initialize()
```suggestion
            .. jupyter-execute::
            
                import ee, geetools
                from geetools.utils import initialize_documentation
                
                initialize_documentation()
```

2025-01-13 18:20 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                # fetch
```suggestion

                # fetch
```

2025-01-13 18:20 UTC, 12rambau commented on geetools/ee_dictionary.py
> +                # process to get desired format
```suggestion

                # process to get desired format
```

2025-01-13 18:22 UTC, 12rambau commented on geetools/ee_dictionary.py
> +            in the `system:index` and the values are in new columns.
type is already written in the proptotye no need to remind it here.

```suggestion
            a collection in which the keys of the :py:class:`ee.Dictionary` are
            in the ``system:index`` and the values are in new columns.
```

2025-01-13 18:22 UTC, 12rambau commented on tests/test_Dictionary.py
> +import geetools  # noqa
You also need to specify which one you want to ignore: 
```suggestion
import geetools  # noqa: F401
```

2025-01-13 18:25 UTC, 12rambau commented on tests/test_Dictionary.py
> +        ee_dict = ee.Dictionary({"ADM0_NAME": "Argentina", "ADM0_CODE": "12"})
Is it still the dictionnary you want to test ? it's a bit weird to have a feature with "ADM0_NAME" and another one "ADM0_CODE". I think the one from the example is more meaningful: 
```python 
d = ee.Dictionary({"foo": 1, "bar": 2})
```

2025-01-13 18:27 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        Examples:
Can you move the Example section as the last item in the docstring ? 
Currently all the example will appear in the documentation before the parameters and the return statement.

2025-01-13 23:12 UTC, fitoprincipe commented on tests/test_Dictionary.py
> +        ee_dict = ee.Dictionary({"ADM0_NAME": "Argentina", "ADM0_CODE": "12"})
I was just tying to mimic FAO's GAUL pattern (level0), but to me is exactly the same as long as it's a `dict` with `str` and/or `int` values.

2025-01-14 12:11 UTC, 12rambau commented on geetools/ee_dictionary.py
> +        3. list: when values are a :py:class:ee.List of numbers or strings,
```suggestion
        3. list: when values are a :py:class:`ee.List` of numbers or strings,
```

2025-01-14 12:48 UTC, 12rambau approved these changes

2025-01-14 12:48 UTC, merged